pipeline:
  # test:
  #   image: node:6
  #   commands:
  #     - cd vue-paper-dashboard-master
  #     - npm install
  #     - npm run unit
  apiTest:
    image: node:6
    commands:
      - sleep 5
      - ping mongo -c 5
      - cd mongoose
      - npm install
      - npm run test
  jenkins:
    image: appleboy/drone-jenkins
    url: http://140.124.181.81:8080
    user: sepass
    token: 48808d94c65b955187e379c9c3a25df1
    job: CD
    when:
      status: [ success ]
  notify:
    image: drillster/drone-email
    host: smtp.mailgun.org
    username: postmaster@drone.ci.io
    password: a72ede7fe93e7ee5ea7598970ea1ab20
    from: DroneCI@drone.io
    recipients: [disc9562@gmail.com]
    when:
      status: [ success, failure ]
services:
  mongo:
    image: mongo:3.0
    command: [ --smallfiles ]