workspace:
  base: /nodejs
  path: src/github.com/disc9562/SE_PASS/vue-paper-dashboard-master
build:
  image: node:6
  commands:
    - npm install
    - npm run unit
environment:
    - DRONE_SERVER=http://140.124.181.81
    - DRONE_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZXh0IjoiZGlzYzk1NjIiLCJ0eXBlIjoidXNlciJ9.8e0DSAalPh11GlRXoouvmyrNpGFaWRqDJXlqB3ORG8Y